### PR TITLE
:book: Update readme with addon contributions link

### PR DESCRIPTION
**Pull request by mikeshng**
## Summary
Update the README with addon contribution repo link

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by mikeshng** [comment]
Doc update like this one should not trigger e2e. 
Did I not do something in the PR?

**Comment by xuezhaojun** [comment]
> Doc update like this one should not trigger e2e. Did I not do something in the PR?

No, I met the same e2e which should not occur, it seems like some thiing addon-framework e2e depends on changed, for example the images it use or the clusteradmin.

**Comment by mikeshng** [comment]
> > Doc update like this one should not trigger e2e. Did I not do something in the PR?
> 
> No, I met the same e2e which should not occur, it seems like some thiing addon-framework e2e depends on changed, for example the images it use or the clusteradmin.

Thanks and go to sleep :sweat_smile:

**Pull request merged**
