### PR TITLE
fix typo AddOnDeloyment

### PR DESCRIPTION
**Pull request by zhiweiyin318**
fix the issue https://github.com/open-cluster-management-io/addon-framework/issues/134

### CODE REVIEW

**Review by qiujian16 — COMMENTED** [review]
directly renaming will be breaking changes, you probably want to still keep the previous as a func aliase and mark them as deprecated.

**Comment by zhiweiyin318** [comment]
> directly renaming will be breaking changes, you probably want to still keep the previous as a func aliase and mark them as deprecated.

@qiujian16  duplicated the typo function since the there is typo in the input and interface definition.  plz take a look again.

**Pull request merged**
