### PR TITLE
update helloworld addon

### PR DESCRIPTION
**Pull request by elgnay**
Signed-off-by: Yang Le <yangle@redhat.com>

### CODE REVIEW

**Review by qiujian16 — COMMENTED** [review]
/approve
/lgtm

**Comment by qiujian16** [comment]
@elgnay https://github.com/open-cluster-management-io/addon-framework/blob/main/.github/workflows/go-presubmit.yml#L120 this need to be changed to v0.11.1

**Comment by elgnay** [comment]
> @elgnay https://github.com/open-cluster-management-io/addon-framework/blob/main/.github/workflows/go-presubmit.yml#L120 this need to be changed to v0.11.1

Updated.

**Pull request merged**
