### PR TITLE
update readme and doc

### PR DESCRIPTION
**Pull request by zhiweiyin318**
Signed-off-by: Zhiwei Yin <zyin@redhat.com>

### CODE REVIEW

**Comment by qiujian16** [comment]
I am thinking just put the readme doc under the example directory and have link on top readme

**Comment by zhiweiyin318** [comment]
@qiujian16 I moved the example readme to the examples dir, and added some other parts in the repo readme. please review.

**Review by qiujian16 — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
